# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb86be547da3ea961b2287d98f90913ec5bdd9b61bc5d7876f50a932e4c0a5a70a5eaa89e3cd97897d8e6c7bea047fe4bf290f90bc4e0b6962bcecc7a2879e1

test:
  secret_key_base: 8e8bb7ab61646ab9167c8270491e3a6bc88a72835a0868edcd538269ce2c1c3ebd6901eb950935c3800fefedb7fc519e584bea767f4d0b14cb6930b8e6208990

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>